### ISSUE TITLE
Destroyed containers are never removed from Matt

### ISSUE THREAD

**Issue by tnagels** [skullydazed/docker2mqtt#3]
I would expect the timeout to also remove destroyed containers from the MQTT topics, but they are retained with status "destroyed". Is there a way to have these automatically removed after some time?

**Comment by skullydazed** [comment]
Looks like I forgot to write the cleanup functionality here. Thanks for bringing it to my attention!

**Comment by skullydazed** [comment]
Fixed in 3972040.
